version: "3"
services:
  # mysql
  mysql:
    image: mysql:9.3.0
    restart: always
    container_name: product_mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    network_mode: bridge
    ports:
        - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: mysqldb
      MYSQL_USEr: jqiu
      MYSQL_PASSWORD: PASSWORD
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # redis
  redis:
    network_mode: bridge
    container_name: product_redis
    image: redis:latest
    ports:
        - 6379:6379
    restart: always

  # PostgreSQL
  postgres:
    image: postgres:16.9  # 
    container_name: product_pgsql
    environment:
      POSTGRES_USER: admin      # 自定义超级用户（默认用户为postgres）
      POSTGRES_PASSWORD: PASSWORD # 密码
      POSTGRES_DB: mydb         # 默认创建的数据库
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data  # 数据持久化
    ports:
      - "5432:5432"            # 默认端口映射
    network_mode: bridge
    restart: always